# : Manager [[[

[mgr]
cwd = { fg = "#dde4e3" }

# Tab
tab_active = { fg = "#003736", bg = "#80d5d2", bold = true }
tab_inactive = { fg = "#9cf1ee", bg = "#00201f" }
tab_width = 1

# Find
find_keyword = { fg = "#ffb4ab", bold = true, italic = true, underline = true }
find_position = { fg = "#ffb4ab", bold = true, italic = true }

# Marker
marker_copied = { fg = "#6ca7ff", bg = "#6ca7ff" }
marker_cut = { fg = "#d2e4ff", bg = "#d2e4ff" }
marker_marked = { fg = "#ffb4ab", bg = "#ffb4ab" }
marker_selected = { fg = "#b2c8e8", bg = "#b2c8e8" }

# Count
count_copied = { fg = "#031d35", bg = "#d2e4ff" }
count_cut = { fg = "#031d35", bg = "#d2e4ff" }
count_selected = { fg = "#003736", bg = "#b2c8e8" }

# Border
border_symbol = " "
border_style  = { fg = "#80d5d2" }

# : ]]]


# : Status [[[

[status]
separator_open = "ü≠Å"
separator_close = "ü≠†"
separator_style = { bg = "#003736", fg = "#F4A261" }

[mode]
# Mode
normal_main = { bg = "#80d5d2", fg = "#003736", bold = true }
normal_alt  = { bg = "#3f4948", fg = "#bec9c7" }

# Select mode
select_main = { bg = "#b0ccca", fg = "#1b3534", bold = true }
select_alt  = { bg = "#3f4948", fg = "#bec9c7" }

# Unset mode
unset_main = { bg = "#b2c8e8", fg = "#1b324b", bold = true }
unset_alt  = { bg = "#3f4948", fg = "#bec9c7" }

# Progress
progress_label = { bold = true }
progress_normal = { fg = "#80d5d2", bg = "#343a3a" }
progress_error = { fg = "#ffb4ab", bg = "#343a3a" }

# Permissions
permissions_t = { fg = "#598a86" }
permissions_w = { fg = "#3c74c5" }
permissions_x = { fg = "#ff2b12" }
permissions_r = { fg = "#3988ff" }
permissions_s = { fg = "#1ed6cf" }

# : ]]]


# : Select [[[

[select]
border = { fg = "#80d5d2" }
active = { fg = "#b2c8e8", bold = true }

# : ]]]


# : Input [[[

[input]
border = { fg = "#80d5d2" }
value = { fg = "#dde4e3" }

# : ]]]

# : Tabs [[[

[tabs]
active = { fg = "#80d5d2", bold = true, bg = "#0e1514" }
inactive = { fg = "#b0ccca", bg = "#0e1514" }
sep_inner = { open = "[", close = "]" }

# : ]]]


# : Completion [[[

[completion]
border = { fg = "#80d5d2", bg = "#003736" }

# : ]]]


# : Tasks [[[

[tasks]
border = { fg = "#80d5d2" }
title = {}
hovered = { fg = "#d2e4ff", underline = true }

# : ]]]


# : Which [[[

[which]
cols = 3
mask = { bg = "#343a3a" }
cand = { fg = "#80d5d2" }
rest = { fg = "#003736" }
desc = { fg = "#dde4e3" }
separator = " ‚ñ∂ "
separator_style = { fg = "#dde4e3" }

# : ]]]


# : Help [[[

[help]
on = { fg = "#dde4e3" }
run = { fg = "#dde4e3" }
footer = { fg = "#1b3534", bg = "#b0ccca" }

# : ]]]


# : Notify [[[

[notify]
title_info = { fg = "#b2c8e8" }
title_warn = { fg = "#80d5d2" }
title_error = { fg = "#ffb4ab" }

# : ]]]


# : File-specific styles [[[

[filetype]

rules = [
    # Images
    { mime = "image/*", fg = "#94e2d5" },

    # Media
    { mime = "{audio,video}/*", fg = "#f9e2af" },

    # Archives
    { mime = "application/{zip,rar,7z*,tar,gzip,xz,zstd,bzip*,lzma,compress,archive,cpio,arj,xar,ms-cab*}", fg = "#f5c2e7" },

    # Documents
    { mime = "application/{pdf,doc,rtf}", fg = "#a6e3a1" },

    # Special files
    { name = "*", is = "orphan", bg = "#93000a" },
    { name = "*", is = "exec", fg = "#ffdad6" },

    # Fallback
    { name = "*", fg = "#dde4e3" },
    { name = "*/", fg = "#80d5d2" },
]

# : ]]]
