[colors.primary]
background = '#0e1514'
foreground = '#dde4e2'
 
[colors.cursor]
text = '#dde4e2'
cursor = '#bec9c7' 
 
[colors.vi_mode_cursor]
text = '#0e1514'
cursor = '#81d5ce' 
 
[colors.search.matches]
foreground = '#3f4947' 
background = '#b0c9e7' 
 
[colors.search.focused_match]
foreground = '#3f4947' 
background = '#81d5ce' 
 
[colors.footer_bar]
foreground = '#3f4947' 
background = '#dde4e2' 
 
[colors.hints.start]
foreground = '#3f4947' 
background = '#b0ccc9' 
 
[colors.hints.end]
foreground = '#3f4947' 
background = '#b0ccc9' 
 
[colors.selection]
text = '#0e1514'
background = '#81d5ce'
 
 
[colors.normal]
black = '#181818' 
red = '#ffb4ab' 
green = '#81d5ce' 
yellow = '#006a65' 
blue = '#81d5ce' 
magenta = '#b0c9e7' 
cyan = '#b0ccc9' 
white = '#BAC2DE' 
 
 
[colors.bright]
black = '#585B70' 
red = '#F38BA8' 
green = '#A6E3A1' 
yellow = '#F9E2AF' 
blue = '#89B4FA' 
magenta = '#F5C2E7' 
cyan = '#94E2D5' 
white = '#A6ADC8' 
 
 
[colors.dim]
black = '#45475A' 
red = '#F38BA8' 
green = '#A6E3A1' 
yellow = '#F9E2AF' 
blue = '#89B4FA' 
magenta = '#F5C2E7' 
cyan = '#94E2D5' 
white = '#BAC2DE' 
