# : Manager [[[

[mgr]
cwd = { fg = "#e9e2d4" }

# Tab
tab_active = { fg = "#3b2f00", bg = "#e0c56d", bold = true }
tab_inactive = { fg = "#fde186", bg = "#231b00" }
tab_width = 1

# Find
find_keyword = { fg = "#ffb4ab", bold = true, italic = true, underline = true }
find_position = { fg = "#ffb4ab", bold = true, italic = true }

# Marker
marker_copied = { fg = "#7bd284", bg = "#7bd284" }
marker_cut = { fg = "#c7eccb", bg = "#c7eccb" }
marker_marked = { fg = "#ffb4ab", bg = "#ffb4ab" }
marker_selected = { fg = "#abcfb0", bg = "#abcfb0" }

# Count
count_copied = { fg = "#01210d", bg = "#c7eccb" }
count_cut = { fg = "#01210d", bg = "#c7eccb" }
count_selected = { fg = "#3b2f00", bg = "#abcfb0" }

# Border
border_symbol = " "
border_style  = { fg = "#e0c56d" }

# : ]]]


# : Status [[[

[status]
separator_open = "ü≠Å"
separator_close = "ü≠†"
separator_style = { bg = "#3b2f00", fg = "#F4A261" }

[mode]
# Mode
normal_main = { bg = "#e0c56d", fg = "#3b2f00", bold = true }
normal_alt  = { bg = "#4b4639", fg = "#cec6b4" }

# Select mode
select_main = { bg = "#d3c6a1", fg = "#383016", bold = true }
select_alt  = { bg = "#4b4639", fg = "#cec6b4" }

# Unset mode
unset_main = { bg = "#abcfb0", fg = "#173720", bold = true }
unset_alt  = { bg = "#4b4639", fg = "#cec6b4" }

# Progress
progress_label = { bold = true }
progress_normal = { fg = "#e0c56d", bg = "#3d392f" }
progress_error = { fg = "#ffb4ab", bg = "#3d392f" }

# Permissions
permissions_t = { fg = "#958146" }
permissions_w = { fg = "#528f5a" }
permissions_x = { fg = "#ff2b12" }
permissions_r = { fg = "#55c561" }
permissions_s = { fg = "#e6b104" }

# : ]]]


# : Select [[[

[select]
border = { fg = "#e0c56d" }
active = { fg = "#abcfb0", bold = true }

# : ]]]


# : Input [[[

[input]
border = { fg = "#e0c56d" }
value = { fg = "#e9e2d4" }

# : ]]]

# : Tabs [[[

[tabs]
active = { fg = "#e0c56d", bold = true, bg = "#16130b" }
inactive = { fg = "#d3c6a1", bg = "#16130b" }
sep_inner = { open = "[", close = "]" }

# : ]]]


# : Completion [[[

[completion]
border = { fg = "#e0c56d", bg = "#3b2f00" }

# : ]]]


# : Tasks [[[

[tasks]
border = { fg = "#e0c56d" }
title = {}
hovered = { fg = "#c7eccb", underline = true }

# : ]]]


# : Which [[[

[which]
cols = 3
mask = { bg = "#3d392f" }
cand = { fg = "#e0c56d" }
rest = { fg = "#3b2f00" }
desc = { fg = "#e9e2d4" }
separator = " ‚ñ∂ "
separator_style = { fg = "#e9e2d4" }

# : ]]]


# : Help [[[

[help]
on = { fg = "#e9e2d4" }
run = { fg = "#e9e2d4" }
footer = { fg = "#383016", bg = "#d3c6a1" }

# : ]]]


# : Notify [[[

[notify]
title_info = { fg = "#abcfb0" }
title_warn = { fg = "#e0c56d" }
title_error = { fg = "#ffb4ab" }

# : ]]]


# : File-specific styles [[[

[filetype]

rules = [
    # Images
    { mime = "image/*", fg = "#94e2d5" },

    # Media
    { mime = "{audio,video}/*", fg = "#f9e2af" },

    # Archives
    { mime = "application/{zip,rar,7z*,tar,gzip,xz,zstd,bzip*,lzma,compress,archive,cpio,arj,xar,ms-cab*}", fg = "#f5c2e7" },

    # Documents
    { mime = "application/{pdf,doc,rtf}", fg = "#a6e3a1" },

    # Special files
    { name = "*", is = "orphan", bg = "#93000a" },
    { name = "*", is = "exec", fg = "#ffdad6" },

    # Fallback
    { name = "*", fg = "#e9e2d4" },
    { name = "*/", fg = "#e0c56d" },
]

# : ]]]
