# : Manager [[[

[mgr]
cwd = { fg = "#e1e4da" }

# Tab
tab_active = { fg = "#14380a", bg = "#a7d394", bold = true }
tab_inactive = { fg = "#c2efae", bg = "#032100" }
tab_width = 1

# Find
find_keyword = { fg = "#ffb4ab", bold = true, italic = true, underline = true }
find_position = { fg = "#ffb4ab", bold = true, italic = true }

# Marker
marker_copied = { fg = "#6cd3d7", bg = "#6cd3d7" }
marker_cut = { fg = "#bcebed", bg = "#bcebed" }
marker_marked = { fg = "#ffb4ab", bg = "#ffb4ab" }
marker_selected = { fg = "#a0cfd1", bg = "#a0cfd1" }

# Count
count_copied = { fg = "#002021", bg = "#bcebed" }
count_cut = { fg = "#002021", bg = "#bcebed" }
count_selected = { fg = "#14380a", bg = "#a0cfd1" }

# Border
border_symbol = " "
border_style  = { fg = "#a7d394" }

# : ]]]


# : Status [[[

[status]
separator_open = "ü≠Å"
separator_close = "ü≠†"
separator_style = { bg = "#14380a", fg = "#F4A261" }

[mode]
# Mode
normal_main = { bg = "#a7d394", fg = "#14380a", bold = true }
normal_alt  = { bg = "#43483f", fg = "#c3c8bc" }

# Select mode
select_main = { bg = "#bccbb1", fg = "#273421", bold = true }
select_alt  = { bg = "#43483f", fg = "#c3c8bc" }

# Unset mode
unset_main = { bg = "#a0cfd1", fg = "#003739", bold = true }
unset_alt  = { bg = "#43483f", fg = "#c3c8bc" }

# Progress
progress_label = { bold = true }
progress_normal = { fg = "#a7d394", bg = "#373a33" }
progress_error = { fg = "#ffb4ab", bg = "#373a33" }

# Permissions
permissions_t = { fg = "#6e885b" }
permissions_w = { fg = "#468e92" }
permissions_x = { fg = "#ff2b12" }
permissions_r = { fg = "#43c7cd" }
permissions_s = { fg = "#62d62e" }

# : ]]]


# : Select [[[

[select]
border = { fg = "#a7d394" }
active = { fg = "#a0cfd1", bold = true }

# : ]]]


# : Input [[[

[input]
border = { fg = "#a7d394" }
value = { fg = "#e1e4da" }

# : ]]]

# : Tabs [[[

[tabs]
active = { fg = "#a7d394", bold = true, bg = "#11140f" }
inactive = { fg = "#bccbb1", bg = "#11140f" }
sep_inner = { open = "[", close = "]" }

# : ]]]


# : Completion [[[

[completion]
border = { fg = "#a7d394", bg = "#14380a" }

# : ]]]


# : Tasks [[[

[tasks]
border = { fg = "#a7d394" }
title = {}
hovered = { fg = "#bcebed", underline = true }

# : ]]]


# : Which [[[

[which]
cols = 3
mask = { bg = "#373a33" }
cand = { fg = "#a7d394" }
rest = { fg = "#14380a" }
desc = { fg = "#e1e4da" }
separator = " ‚ñ∂ "
separator_style = { fg = "#e1e4da" }

# : ]]]


# : Help [[[

[help]
on = { fg = "#e1e4da" }
run = { fg = "#e1e4da" }
footer = { fg = "#273421", bg = "#bccbb1" }

# : ]]]


# : Notify [[[

[notify]
title_info = { fg = "#a0cfd1" }
title_warn = { fg = "#a7d394" }
title_error = { fg = "#ffb4ab" }

# : ]]]


# : File-specific styles [[[

[filetype]

rules = [
    # Images
    { mime = "image/*", fg = "#94e2d5" },

    # Media
    { mime = "{audio,video}/*", fg = "#f9e2af" },

    # Archives
    { mime = "application/{zip,rar,7z*,tar,gzip,xz,zstd,bzip*,lzma,compress,archive,cpio,arj,xar,ms-cab*}", fg = "#f5c2e7" },

    # Documents
    { mime = "application/{pdf,doc,rtf}", fg = "#a6e3a1" },

    # Special files
    { name = "*", is = "orphan", bg = "#93000a" },
    { name = "*", is = "exec", fg = "#ffdad6" },

    # Fallback
    { name = "*", fg = "#e1e4da" },
    { name = "*/", fg = "#a7d394" },
]

# : ]]]
