# Symphony by vyrx
# Theme: Matugen (Dynamic)
# https://github.com/vyrx-dev

# : Manager [[[

[mgr]
cwd = { fg = "#e1e2e8" }

# Tab
tab_active = { fg = "#00325a", bg = "#a2c9fd", bold = true }
tab_inactive = { fg = "#d2e4ff", bg = "#001c37" }
tab_width = 1

# Find
find_keyword = { fg = "#ffb4ab", bold = true, italic = true, underline = true }
find_position = { fg = "#ffb4ab", bold = true, italic = true }

# Marker
marker_copied = { fg = "#d674ff", bg = "#d674ff" }
marker_cut = { fg = "#f4daff", bg = "#f4daff" }
marker_marked = { fg = "#ffb4ab", bg = "#ffb4ab" }
marker_selected = { fg = "#d8bde4", bg = "#d8bde4" }

# Count
count_copied = { fg = "#261431", bg = "#f4daff" }
count_cut = { fg = "#261431", bg = "#f4daff" }
count_selected = { fg = "#00325a", bg = "#d8bde4" }

# Border
border_symbol = " "
border_style  = { fg = "#a2c9fd" }

# : ]]]


# : Status [[[

[status]
separator_open = "ü≠Å"
separator_close = "ü≠†"
separator_style = { bg = "#00325a", fg = "#F4A261" }

[mode]
# Mode
normal_main = { bg = "#a2c9fd", fg = "#00325a", bold = true }
normal_alt  = { bg = "#43474e", fg = "#c3c6cf" }

# Select mode
select_main = { bg = "#bbc7db", fg = "#253141", bold = true }
select_alt  = { bg = "#43474e", fg = "#c3c6cf" }

# Unset mode
unset_main = { bg = "#d8bde4", fg = "#3c2947", bold = true }
unset_alt  = { bg = "#43474e", fg = "#c3c6cf" }

# Progress
progress_label = { bold = true }
progress_normal = { fg = "#a2c9fd", bg = "#37393e" }
progress_error = { fg = "#ffb4ab", bg = "#37393e" }

# Permissions
permissions_t = { fg = "#5875a5" }
permissions_w = { fg = "#9850b8" }
permissions_x = { fg = "#ff2b12" }
permissions_r = { fg = "#c741ff" }
permissions_s = { fg = "#3988ff" }

# : ]]]


# : Select [[[

[select]
border = { fg = "#a2c9fd" }
active = { fg = "#d8bde4", bold = true }

# : ]]]


# : Input [[[

[input]
border = { fg = "#a2c9fd" }
value = { fg = "#e1e2e8" }

# : ]]]

# : Tabs [[[

[tabs]
active = { fg = "#a2c9fd", bold = true, bg = "#111418" }
inactive = { fg = "#bbc7db", bg = "#111418" }
sep_inner = { open = "[", close = "]" }

# : ]]]


# : Completion [[[

[completion]
border = { fg = "#a2c9fd", bg = "#00325a" }

# : ]]]


# : Tasks [[[

[tasks]
border = { fg = "#a2c9fd" }
title = {}
hovered = { fg = "#f4daff", underline = true }

# : ]]]


# : Which [[[

[which]
cols = 3
mask = { bg = "#37393e" }
cand = { fg = "#a2c9fd" }
rest = { fg = "#00325a" }
desc = { fg = "#e1e2e8" }
separator = " ‚ñ∂ "
separator_style = { fg = "#e1e2e8" }

# : ]]]


# : Help [[[

[help]
on = { fg = "#e1e2e8" }
run = { fg = "#e1e2e8" }
footer = { fg = "#253141", bg = "#bbc7db" }

# : ]]]


# : Notify [[[

[notify]
title_info = { fg = "#d8bde4" }
title_warn = { fg = "#a2c9fd" }
title_error = { fg = "#ffb4ab" }

# : ]]]


# : File-specific styles [[[

[filetype]

rules = [
    # Images
    { mime = "image/*", fg = "#94e2d5" },

    # Media
    { mime = "{audio,video}/*", fg = "#f9e2af" },

    # Archives
    { mime = "application/{zip,rar,7z*,tar,gzip,xz,zstd,bzip*,lzma,compress,archive,cpio,arj,xar,ms-cab*}", fg = "#f5c2e7" },

    # Documents
    { mime = "application/{pdf,doc,rtf}", fg = "#a6e3a1" },

    # Special files
    { name = "*", is = "orphan", bg = "#93000a" },
    { name = "*", is = "exec", fg = "#ffdad6" },

    # Fallback
    { name = "*", fg = "#e1e2e8" },
    { name = "*/", fg = "#a2c9fd" },
]

# : ]]]
