# Symphony by vyrx
# Theme: Void
# https://github.com/vyrx-dev

# : Manager [[[

[mgr]
cwd = { fg = "#DECCFF" }

# Tab
tab_active = { fg = "#05010C", bg = "#BB9AF7", bold = true }
tab_inactive = { fg = "#C3AAF0", bg = "#0f0a16" }
tab_width = 1

# Find
find_keyword = { fg = "#FFFFFF", bold = true, italic = true, underline = true }
find_position = { fg = "#FFFFFF", bold = true, italic = true }

# Marker
marker_copied = { fg = "#A6B8FF", bg = "#A6B8FF" }
marker_cut = { fg = "#FF8A95", bg = "#FF8A95" }
marker_marked = { fg = "#C2B8FF", bg = "#C2B8FF" }
marker_selected = { fg = "#B49AE6", bg = "#B49AE6" }

# Count
count_copied = { fg = "#05010C", bg = "#A6B8FF" }
count_cut = { fg = "#05010C", bg = "#FF8A95" }
count_selected = { fg = "#05010C", bg = "#B49AE6" }

# Border
border_symbol = " "
border_style  = { fg = "#6B578F" }

# : ]]]


# : Status [[[

[status]
separator_open = "ü≠Å"
separator_close = "ü≠†"
separator_style = { bg = "#382952", fg = "#B49AE6" }

[mode]
# Mode
normal_main = { bg = "#BB9AF7", fg = "#05010C", bold = true }
normal_alt  = { bg = "#382952", fg = "#C3AAF0" }

# Select mode
select_main = { bg = "#C2B8FF", fg = "#05010C", bold = true }
select_alt  = { bg = "#382952", fg = "#C3AAF0" }

# Unset mode
unset_main = { bg = "#B49AE6", fg = "#05010C", bold = true }
unset_alt  = { bg = "#382952", fg = "#C3AAF0" }

# Progress
progress_label = { bold = true }
progress_normal = { fg = "#BB9AF7", bg = "#0f0a16" }
progress_error = { fg = "#FF8A95", bg = "#0f0a16" }

# Permissions
permissions_t = { fg = "#CBA6F8" }
permissions_w = { fg = "#B49AE6" }
permissions_x = { fg = "#FF8A95" }
permissions_r = { fg = "#C2B8FF" }
permissions_s = { fg = "#A6B8FF" }

# : ]]]


# : Select [[[

[select]
border = { fg = "#6B578F" }
active = { fg = "#BB9AF7", bold = true }

# : ]]]


# : Input [[[

[input]
border = { fg = "#6B578F" }
value = { fg = "#DECCFF" }

# : ]]]

# : Tabs [[[

[tabs]
active = { fg = "#BB9AF7", bold = true, bg = "#05010C" }
inactive = { fg = "#6B578F", bg = "#05010C" }
sep_inner = { open = "[", close = "]" }

# : ]]]


# : Completion [[[

[completion]
border = { fg = "#6B578F", bg = "#382952" }

# : ]]]


# : Tasks [[[

[tasks]
border = { fg = "#6B578F" }
title = {}
hovered = { fg = "#C2B8FF", underline = true }

# : ]]]


# : Which [[[

[which]
cols = 3
mask = { bg = "#0f0a16" }
cand = { fg = "#BB9AF7" }
rest = { fg = "#6B578F" }
desc = { fg = "#DECCFF" }
separator = " ‚ñ∂ "
separator_style = { fg = "#C3AAF0" }

# : ]]]


# : Help [[[

[help]
on = { fg = "#DECCFF" }
run = { fg = "#DECCFF" }
footer = { fg = "#05010C", bg = "#C2B8FF" }

# : ]]]


# : Notify [[[

[notify]
title_info = { fg = "#A6B8FF" }
title_warn = { fg = "#DDCCFF" }
title_error = { fg = "#FF8A95" }

# : ]]]


# : File-specific styles [[[

[filetype]

rules = [
    # Images
    { mime = "image/*", fg = "#A6B8FF" },

    # Media
    { mime = "{audio,video}/*", fg = "#DDCCFF" },

    # Archives
    { mime = "application/{zip,rar,7z*,tar,gzip,xz,zstd,bzip*,lzma,compress,archive,cpio,arj,xar,ms-cab*}", fg = "#C4AAF0" },

    # Documents
    { mime = "application/{pdf,doc,rtf}", fg = "#B3A8F7" },

    # Special files
    { name = "*", is = "orphan", bg = "#F07178" },
    { name = "*", is = "exec", fg = "#FFFFFF" },

    # Fallback
    { name = "*", fg = "#DECCFF" },
    { name = "*/", fg = "#BB9AF7" },
]

# : ]]]
