[config]

[templates.hyprland]
input_path = '/home/vyrx/.config/matugen/templates/hyprland-colors.conf'
# output_path = '~/.config/hypr/colors.conf'
output_path = '~/dotfiles/themes/matugen/.config/hypr/colors.conf'
post_hook = 'hyprctl reload'

[templates.kitty]
input_path = '/home/vyrx/.config/matugen/templates/kitty-colors.conf'
# output_path = '~/.config/kitty/colors.conf'
output_path = '~/dotfiles/themes/matugen/.config/kitty/colors.conf'
post_hook = 'pkill -SIGUSR1 kitty'


[templates.btop]
input_path = '/home/vyrx/.config/matugen/templates/btop.theme'
# output_path = '~/.config/btop/themes/matugen.theme'
output_path = '~/dotfiles/themes/matugen/.config/btop/themes/current.theme'

[templates.pywalfox]
input_path = '/home/vyrx/.config/matugen/templates/pywalfox-colors.json'
output_path = '~/dotfiles/themes/matugen/.cache/wal/colors.json'
post_hook = 'pywalfox update'

[templates.yazi]
input_path = '/home/vyrx/.config/matugen/templates/yazi-theme.toml'
output_path = '~/dotfiles/themes/matugen/.config/yazi/theme.toml'

[templates.cava]
input_path = '~/.config/matugen/templates/cava-colors.ini'
output_path = '~/dotfiles/themes/matugen/.config/cava/colors.ini'
post_hook = "pkill -USR1 cava"

[templates.vesktop]
input_path = '~/.config/matugen/templates/midnight-color.css'
output_path = '~/dotfiles/themes/matugen/.config/vesktop/themes/midnight-discord.css'

[templates.fuzzel]
input_path = '~/.config/matugen/templates/fuzzel_theme.ini'
output_path = '~/dotfiles/themes/matugen/.config/fuzzel/fuzzel_theme.ini'

[templates.ghostty]
input_path = '~/.config/matugen/templates/ghostty'
# output_path = '~/.config/ghostty/themes/Matugen'
output_path = '~/dotfiles/themes/matugen/.config/ghostty/themes/colors'
post_hook = 'pkill -SIGUSR2 ghostty'

[templates.waybar]
input_path = '~/.config/matugen/templates/colors.css'
output_path = '~/dotfiles/themes/matugen/.config/waybar/colors.css'
post_hook = 'pkill -SIGUSR2 waybar'

[templates.starship]
input_path = '~/.config/matugen/templates/starship-colors.toml'
output_path = '~/dotfiles/themes/matugen/.config/starship.toml'
post_hook = '/home/vyrx/dotfiles/theme-scripts/core/update-obsidian-theme.sh'

[templates.rofi]
input_path = '~/.config/matugen/templates/rofi-colors.rasi'
output_path = '~/dotfiles/themes/matugen/.config/rofi/colors.rasi'

[templates.swaync]
input_path = '~/.config/matugen/templates/colors.css'
output_path = '~/dotfiles/themes/matugen/.config/swaync/matugen/colors.css'

[templates.gtk3]
input_path = '~/.config/matugen/templates/gtk-colors.css'
output_path = '~/dotfiles/themes/matugen/.config/gtk-3.0/colors.css'

[templates.alacritty]
input_path = '~/.config/matugen/templates/alacritty-colors.toml'
output_path = '~/dotfiles/themes/matugen/.config/alacritty/colors.toml'

[templates.gtk4]
input_path = '~/.config/matugen/templates/gtk-colors.css'
output_path = '~/dotfiles/themes/matugen/.config/gtk-4.0/colors.css'

[templates.rmpc]
input_path = '~/.config/matugen/templates/rmpc-theme.ron'
output_path = '~/dotfiles/themes/matugen/.config/rmpc/themes/current.ron'


