add_newline = false
command_timeout = 60
format = """\
$os \
$directory \
$git_branch$git_status\
$line_break\
$character\
"""

# right_format = """\
# $time\
# """

palette = "colors"

[palettes.colors]
mustard = '#af8700' # example
color1 = '#81d5ce'
color2 = '#003734'
color3 = '#bec9c7'
color4 = '#1a2120'
color5 = '#003734'
color6 = '#0e1514'
color7 = '#0e1514'
color8 = '#81d5ce'
color9 = '#b0c9e7'

[directory]
style = "fg:#81d5ce bold" # color1
read_only = " 󰌾"
read_only_style = "fg:#ea6962" # dark blue
truncation_length = 0
truncate_to_repo = false
format = "[$path]($style)[$read_only]($read_only_style)"

[directory.substitutions]
'~/100xCodes/Cohort-3-WebDev' = 'Learning'
'~/Testing-repo' = 'work-project'

[character]
success_symbol = '[❯](fg:#81d5ce bold)'
error_symbol = '[❯](fg:#ffb4ab bold)'
vicmd_symbol = '[❮](fg:#0e1514 bold)'

[git_branch]
style = "fg:#b0c9e7 bold" # color9 (red)
format = '[$symbol$branch]($style) '

[git_status]
ahead = '⇡${count}'
behind = '⇣${count}'
diverged = '⇕⇡${ahead_count}⇣${behind_count}'
format = '[[($all_status$ahead_behind )](fg:#ea6962)]($style)'
# style = "bg:#394260"

[os]
format = "[$symbol]($style)"
style = "fg:#81d5ce bold" # color8
disabled = false

[os.symbols]
Linux = "󰊠 "
Arch = "󰣇"
Ubuntu = "󰕈"

# [time]
# disabled = false
# format = '[[ $time ](fg:#ea6962 )]($style)'
# time_format = "%R"

[line_break]
disabled = true

