# Symphony by vyrx
# Theme: Zen
# https://github.com/vyrx-dev

add_newline = false
command_timeout = 60
format = """\
$os \
$directory \
$git_branch$git_status\
$line_break\
$character\
"""

# right_format = """\
# $time\
# """

palette = "colors"

[palettes.colors]
color1 = '#959595'
color2 = '#2a2a2a'
color3 = '#c8c8c8'
color4 = '#1a1a1a'
color5 = '#505050'
color6 = '#0f0f0f'
color7 = '#0f0f0f'
color8 = '#959595'
color9 = '#787878'

[directory]
style = "fg:#959595 bold" # color1
read_only = " 󰌾"
read_only_style = "fg:#505050" # darker gray
truncation_length = 0
truncate_to_repo = false
format = "[$path]($style)[$read_only]($read_only_style)"

[directory.substitutions]
'~/100xCodes/Cohort-3-WebDev' = 'Learning'
'~/Testing-repo' = 'work-project'

[character]
success_symbol = '[❯](fg:#959595 bold)'
error_symbol = '[❯](fg:#505050 bold)'
vicmd_symbol = '[❮](fg:#0f0f0f bold)'

[git_branch]
style = "fg:#787878 bold" # color9
format = '[$symbol$branch]($style) '

[git_status]
ahead = '⇡${count}'
behind = '⇣${behind_count}'
diverged = '⇕⇡${ahead_count}⇣${behind_count}'
format = '[[($all_status$ahead_behind )](fg:#656565)]($style)'

[os]
format = "[$symbol]($style)"
style = "fg:#959595 bold" # color8
disabled = false

[os.symbols]
Linux = "󰊠 "
Arch = "󰣇"
Ubuntu = "󰕈"

# [time]
# disabled = false
# format = '[[ $time ](fg:#656565 )]($style)'
# time_format = "%R"

[line_break]
disabled = true

