# Symphony
# Author: vyrx
# Theme: Sakura

add_newline = false
command_timeout = 60
format = """\
$os \
$directory \
$git_branch$git_status\
$line_break\
$character\
"""

# right_format = """\
# $time\
# """

palette = "colors"

[palettes.colors]
color1 = '#E8C099'
color2 = '#4a3c45'
color3 = '#f0eaed'
color4 = '#0d0509'
color5 = '#4a3c45'
color6 = '#0d0509'
color7 = '#0d0509'
color8 = '#E8C099'
color9 = '#D1B399'

[directory]
style = "fg:color1 bold"
read_only = " 󰌾"
read_only_style = "fg:#E85F6F"
truncation_length = 0
truncate_to_repo = false
format = "[$path]($style)[$read_only]($read_only_style)"

[directory.substitutions]
'~/100xCodes/Cohort-3-WebDev' = 'Learning'
'~/Testing-repo' = 'work-project'

[character]
success_symbol = '[❯](fg:color8 bold)'
error_symbol = '[❯](fg:#E85F6F bold)'
vicmd_symbol = '[❮](fg:color6 bold)'

[git_branch]
style = "fg:color9 bold"
format = '[$symbol$branch]($style) '

[git_status]
ahead = '⇡${count}'
behind = '⇣${count}'
diverged = '⇕⇡${ahead_count}⇣${behind_count}'
format = '[[($all_status$ahead_behind )](fg:#E85F6F)]($style)'
# style = "bg:#394260"

[os]
format = "[$symbol]($style)"
style = "fg:color8 bold"
disabled = false

[os.symbols]
Linux = "󰊠 "
Arch = "󰣇"
Ubuntu = "󰕈"

# [time]
# disabled = false
# format = '[[ $time ](fg:#E85F6F )]($style)'
# time_format = "%R"

[line_break]
disabled = true

