# Symphony by vyrx / Theme: Forest / https://github.com/vyrx-dev
add_newline = false
command_timeout = 60
format = """\
$os \
$directory \
$git_branch$git_status\
$line_break\
$character\
"""

# right_format = """\
# $time\
# """

palette = "colors"

[palettes.colors]
mustard = '#af8700' # example
color1 = '#70cf6c'
color2 = '#020802'
color3 = '#b4e8b2'
color4 = '#0a1a0a'
color5 = '#4a7a4a'
color6 = '#020802'
color7 = '#fdfffd'
color8 = '#62e2a4'
color9 = '#9ed8dd'

[directory]
style = "fg:#70cf6c bold" # color1
read_only = " 󰌾"
read_only_style = "fg:#bf5a7c" # forest red
truncation_length = 0
truncate_to_repo = false
format = "[$path]($style)[$read_only]($read_only_style)"

[directory.substitutions]
'~/100xCodes/Cohort-3-WebDev' = 'Learning'
'~/Testing-repo' = 'work-project'

[character]
success_symbol = '[❯](fg:#DFEC63 bold)'
error_symbol = '[❯](fg:#bf5a7c bold)'
vicmd_symbol = '[❮](fg:#020802 bold)'

[git_branch]
style = "fg:#DFEC63 bold" # yellow
format = '[$symbol$branch]($style) '

[git_status]
ahead = '⇡${count}'
behind = '⇣${count}'
diverged = '⇕⇡${ahead_count}⇣${behind_count}'
format = '[[($all_status$ahead_behind )](fg:#bf5a7c)]($style)'
# style = "bg:#394260"

[os]
format = "[$symbol]($style)"
style = "fg:#70cf6c bold" # color8
disabled = false

[os.symbols]
Linux = "󰊠 "
Arch = "󰣇"
Ubuntu = "󰕈"

# [time]
# disabled = false
# format = '[[ $time ](fg:#bf5a7c )]($style)'
# time_format = "%R"

[line_break]
disabled = true
