# Symphony by vyrx
# Theme: Void
# https://github.com/vyrx-dev

add_newline = false
command_timeout = 60
format = """\
$os \
$directory \
$git_branch$git_status\
$line_break\
$character\
"""

# right_format = """\
# $time\
# """

palette = "colors"

[palettes.colors]
color1 = '#BB9AF7'
color2 = '#382952'
color3 = '#C3AAF0'
color4 = '#6B578F'
color5 = '#B49AE6'
color6 = '#05010C'
color7 = '#0f0a16'
color8 = '#A6B8FF'
color9 = '#C2B8FF'

[directory]
style = "fg:#BB9AF7 bold"
read_only = " 󰌾"
read_only_style = "fg:#FF8A95"
truncation_length = 0
truncate_to_repo = false
format = "[$path]($style)[$read_only]($read_only_style)"

[directory.substitutions]
'~/100xCodes/Cohort-3-WebDev' = 'Learning'
'~/Testing-repo' = 'work-project'

[character]
success_symbol = '[❯](fg:#BB9AF7 bold)'
error_symbol = '[❯](fg:#FF8A95 bold)'
vicmd_symbol = '[❮](fg:#6B578F bold)'

[git_branch]
style = "fg:#C2B8FF bold"
format = '[$symbol$branch]($style) '

[git_status]
ahead = '⇡${count}'
behind = '⇣${count}'
diverged = '⇕⇡${ahead_count}⇣${behind_count}'
format = '[[($all_status$ahead_behind )](fg:#FF8A95)]($style)'

[os]
format = "[$symbol]($style)"
style = "fg:#BB9AF7 bold"
disabled = false

[os.symbols]
Linux = "󰊠 "
Arch = "󰣇"
Ubuntu = "󰕈"

# [time]
# disabled = false
# format = '[[ $time ](fg:#ea6962 )]($style)'
# time_format = "%R"

[line_break]
disabled = true

