[colors]
[colors.primary]
background = "#111311"
foreground = "#ececed"

[colors.normal]
black   = "#111311"
red     = "#d38355"
green   = "#96a199"
yellow  = "#a6a6a0"
blue    = "#9cb1b9"
magenta = "#e2ab83"
cyan    = "#adc1c7"
white   = "#BDBDC0"

[colors.bright]
black   = "#4e534e"
red     = "#e9b79a"
green   = "#c6cdc8"
yellow  = "#d3d3cf"
blue    = "#d1dce0"
magenta = "#f5ddcc"
cyan    = "#e3eaed"
white   = "#ececed"

[colors.cursor]
text   = "#111311"
cursor = "#ececed"
