add_newline = true
command_timeout = 60
# palette = "gruvbox_material"
format = """\
$os \
$directory\
$golang\
$nodejs\
$git_branch$git_status\
$line_break\
$character\
"""

# right_format = """\
# $time\
# """

[directory.substitutions]
'~/100xCodes/Cohort-3-WebDev' = 'Learning'
'~/Testing-repo' = 'work-project'

palette = "colors"

[palettes.colors]
mustard = '#af8700' # example
color1 = '{{colors.primary_fixed_dim.default.hex}}'
color2 = '{{colors.on_primary.default.hex}}'
color3 = '{{colors.on_surface_variant.default.hex}}'
color4 = '{{colors.surface_container.default.hex}}'
color5 = '{{colors.on_primary.default.hex}}'
color6 = '{{colors.surface_dim.default.hex}}'
color7 = '{{colors.surface.default.hex}}'
color8 = '{{colors.primary.default.hex}}'
color9 = '{{colors.tertiary.default.hex}}'

[character]
success_symbol = '[❯](color9 bold)'         # mustard
error_symbol = '[❯](@{error})' # color9
vicmd_symbol = '[❮](#f9e2af))'  # color8

[directory]
style = "fg:{{colors.primary_fixed_dim.default.hex}} bold" # color1
read_only = " 󰌾"
truncation_length = 0
truncate_to_repo = false
format = "[$path]($style)[$read_only ]($read_only_style)"

[git_branch]
style = "fg:{{colors.tertiary.default.hex}} bold" # color9 (red)
format = '[ $symbol$branch]($style) '

[git_status]
ahead = '⇡${count}'
behind = '⇣${count}'
diverged = '⇕⇡${ahead_count}⇣${behind_count}'
format = '[[($all_status$ahead_behind )](fg:#ea6962)]($style)'
# style = "bg:#394260"
#

[os]
format = "[$symbol]($style)"
style = "fg:{{colors.primary.default.hex}} bold" # color8
disabled = false

[os.symbols]
Arch = "󰣇"
Linux = "󰊠"
Ubuntu = "󰕈"

[golang]
format = "[$symbol]($style)"
style = "fg:{{colors.surface_container.default.hex}} bold"
symbol = ""

[nodejs]
format = "[$symbol]($style)"
style = "fg:{{colors.on_surface_variant.default.hex}} bold"
symbol = "󰎙 "


# [time]
# disabled = false
# format = '[[ $time ](fg:#ea6962 )]($style)'
# time_format = "%R"

[line_break]
disabled = true

