# : Manager [[[

[mgr]
cwd = { fg = "#e0e2e8" }

# Tab
tab_active = { fg = "#003354", bg = "#9ccbfb", bold = true }
tab_inactive = { fg = "#cee5ff", bg = "#001d33" }
tab_width = 1

# Find
find_keyword = { fg = "#ffb4ab", bold = true, italic = true, underline = true }
find_position = { fg = "#ffb4ab", bold = true, italic = true }

# Marker
marker_copied = { fg = "#c275ff", bg = "#c275ff" }
marker_cut = { fg = "#efdbff", bg = "#efdbff" }
marker_marked = { fg = "#ffb4ab", bg = "#ffb4ab" }
marker_selected = { fg = "#d3bfe6", bg = "#d3bfe6" }

# Count
count_copied = { fg = "#231533", bg = "#efdbff" }
count_cut = { fg = "#231533", bg = "#efdbff" }
count_selected = { fg = "#003354", bg = "#d3bfe6" }

# Border
border_symbol = " "
border_style  = { fg = "#9ccbfb" }

# : ]]]


# : Status [[[

[status]
separator_open = "ü≠Å"
separator_close = "ü≠†"
separator_style = { bg = "#003354", fg = "#F4A261" }

[mode]
# Mode
normal_main = { bg = "#9ccbfb", fg = "#003354", bold = true }
normal_alt  = { bg = "#42474e", fg = "#c2c7cf" }

# Select mode
select_main = { bg = "#b9c8da", fg = "#243240", bold = true }
select_alt  = { bg = "#42474e", fg = "#c2c7cf" }

# Unset mode
unset_main = { bg = "#d3bfe6", fg = "#392a49", bold = true }
unset_alt  = { bg = "#42474e", fg = "#c2c7cf" }

# Progress
progress_label = { bold = true }
progress_normal = { fg = "#9ccbfb", bg = "#36393e" }
progress_error = { fg = "#ffb4ab", bg = "#36393e" }

# Permissions
permissions_t = { fg = "#5679a4" }
permissions_w = { fg = "#8751bb" }
permissions_x = { fg = "#ff2b12" }
permissions_r = { fg = "#ab42ff" }
permissions_s = { fg = "#3594ff" }

# : ]]]


# : Select [[[

[select]
border = { fg = "#9ccbfb" }
active = { fg = "#d3bfe6", bold = true }

# : ]]]


# : Input [[[

[input]
border = { fg = "#9ccbfb" }
value = { fg = "#e0e2e8" }

# : ]]]

# : Tabs [[[

[tabs]
active = { fg = "#9ccbfb", bold = true, bg = "#101418" }
inactive = { fg = "#b9c8da", bg = "#101418" }
sep_inner = { open = "[", close = "]" }

# : ]]]


# : Completion [[[

[completion]
border = { fg = "#9ccbfb", bg = "#003354" }

# : ]]]


# : Tasks [[[

[tasks]
border = { fg = "#9ccbfb" }
title = {}
hovered = { fg = "#efdbff", underline = true }

# : ]]]


# : Which [[[

[which]
cols = 3
mask = { bg = "#36393e" }
cand = { fg = "#9ccbfb" }
rest = { fg = "#003354" }
desc = { fg = "#e0e2e8" }
separator = " ‚ñ∂ "
separator_style = { fg = "#e0e2e8" }

# : ]]]


# : Help [[[

[help]
on = { fg = "#e0e2e8" }
run = { fg = "#e0e2e8" }
footer = { fg = "#243240", bg = "#b9c8da" }

# : ]]]


# : Notify [[[

[notify]
title_info = { fg = "#d3bfe6" }
title_warn = { fg = "#9ccbfb" }
title_error = { fg = "#ffb4ab" }

# : ]]]


# : File-specific styles [[[

[filetype]

rules = [
    # Images
    { mime = "image/*", fg = "#94e2d5" },

    # Media
    { mime = "{audio,video}/*", fg = "#f9e2af" },

    # Archives
    { mime = "application/{zip,rar,7z*,tar,gzip,xz,zstd,bzip*,lzma,compress,archive,cpio,arj,xar,ms-cab*}", fg = "#f5c2e7" },

    # Documents
    { mime = "application/{pdf,doc,rtf}", fg = "#a6e3a1" },

    # Special files
    { name = "*", is = "orphan", bg = "#93000a" },
    { name = "*", is = "exec", fg = "#ffdad6" },

    # Fallback
    { name = "*", fg = "#e0e2e8" },
    { name = "*/", fg = "#9ccbfb" },
]

# : ]]]
